### PR TITLE
Fix Spotify Creation of Playlist bug 

### LINKED ISSUE #37: [BUG] spotify api not allowing creation of playlist
### Description

Everything works fine until it gets to creating the playlist with the spotify api
Problem should be around here:
https://github.com/Dun-sin/HearItFresh/blob/a3f0b0acad51db8b5bbd7317e8cd77032503936a/app/lib/spotify.ts#L27-L50

### Screenshots

Image

### Additional information

_No response_

### 🥦 Browser

Microsoft Edge

### 👀 Have you checked if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [x] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/HearItFresh/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

### PR DESCRIPTION
**Pull request by divineamunega**
# Fixes Issue

**This PR closes #37 **

## 👨‍💻 Changes proposed(What did you do ?)
I fixed the spotify creation bug. It was caused by the spotify library not correctly saving the access token during auth
## ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

## Note to reviewers

Please note that this PR includes changes to the database. 
      For these changes to work correctly, you will also need to 
      update your database schema and install Prisma, as requested
      by the maintainer. You can find a hosted version of my branch at https://hear-it-fresh.vercel.app/ to check out my changes

## 📷 Screenshots
image

### CODE REVIEW

File: app/api/auth/refreshToken/route.ts [hunk 1]
```diff
@@ -1,42 +1,43 @@
-import axios, { AxiosError } from 'axios';
+import axios, { AxiosError } from "axios";
 
-import { NextResponse } from 'next/server';
-import { getUser } from '@/app/lib/spotify';
+import { NextResponse } from "next/server";
+import { getUser } from "@/app/lib/spotify";
```
Comment (Dun-sin) [inline app/api/auth/refreshToken/route.ts:4]:
```suggestion
import { NextResponse } from 'next/server';
import { getUser } from '@/app/lib/spotify';
```

File: app/api/auth/refreshToken/route.ts [hunk 2]
```diff
@@ -1,42 +1,43 @@
...
 const client_secret = process.env.SPOTIFY_CLIENT_SECRET;
 
 export async function POST(req: Request) {
 	const res = await req.json();
 	const refreshToken = res.refresh_token;
+	console.log("Refresh Token", refreshToken);
 
 	if (!refreshToken) {
-		return Response.json({ error: 'Invalid request' }, { status: 400 });
+		return Response.json({ error: "Invalid request" }, { status: 400 });
```
Comment (Dun-sin) [inline app/api/auth/refreshToken/route.ts:15]:
```suggestion
		return Response.json({ error: 'Invalid request' }, { status: 400 });
```

File: app/api/auth/refreshToken/route.ts [hunk 3]
```diff
@@ -1,42 +1,43 @@
...
 	}
 
 	try {
 		const response = await axios.post(
-			'https://accounts.spotify.com/api/token',
+			"https://accounts.spotify.com/api/token",
```
Comment (Dun-sin) [inline app/api/auth/refreshToken/route.ts:20]:
```suggestion
			'https://accounts.spotify.com/api/token',
```

File: app/api/auth/refreshToken/route.ts [hunk 4]
```diff
@@ -1,42 +1,43 @@
...
 			{
-				grant_type: 'refresh_token',
+				grant_type: "refresh_token",
```
Comment (Dun-sin) [inline app/api/auth/refreshToken/route.ts:22]:
```suggestion
				grant_type: 'refresh_token',
```

File: app/api/auth/refreshToken/route.ts [hunk 5]
```diff
@@ -1,42 +1,43 @@
...
 				client_id,
 				refresh_token: refreshToken,
 			},
 			{
 				headers: {
-					'content-Type': 'application/x-www-form-urlencoded',
+					"content-Type": "application/x-www-form-urlencoded",
```
Comment (Dun-sin) [inline app/api/auth/refreshToken/route.ts:28]:
```suggestion
					"content-Type": 'application/x-www-form-urlencoded',
```

File: app/api/auth/refreshToken/route.ts [hunk 6]
```diff
@@ -1,42 +1,43 @@
...
 					Authorization:
-						'Basic ' +
-						Buffer.from(client_id + ':' + client_secret).toString('base64'),
+						"Basic " +
+						Buffer.from(client_id + ":" + client_secret).toString("base64"),
```
Comment (Dun-sin) [inline app/api/auth/refreshToken/route.ts:31]:
```suggestion
						'Basic ' +
						Buffer.from(client_id + ':' + client_secret).toString('base64'),
```

File: app/api/auth/refreshToken/route.ts [hunk 7]
```diff
@@ -1,42 +1,43 @@
...
-			},
+			}
 		);
 
 		const { access_token, refresh_token, expires_in } = response.data;
 		const user = await getUser(access_token);
 		return NextResponse.json(
 			{ expires_in, refresh_token, access_token, user },
-			{ status: 200 },
+			{ status: 200 }
```
Comment (Dun-sin) [inline app/api/auth/refreshToken/route.ts:40]:
```suggestion
			{ status: 200 },
```

File: app/api/auth/refreshToken/route.ts [hunk 8]
```diff
@@ -24,7 +24,7 @@ export async function POST(req: Request) {
 			},
 			{
 				headers: {
-					'content-Type': 'application/x-www-form-urlencoded',
+					"content-Type": 'application/x-www-form-urlencoded',
```
Comment (Dun-sin) [inline app/api/auth/refreshToken/route.ts:27]:
```suggestion
					'content-Type': 'application/x-www-form-urlencoded',
```

File: app/api/auth/route.ts [hunk 9]
```diff
@@ -11,44 +12,58 @@ const client_secret = process.env.SPOTIFY_CLIENT_SECRET;
...
+			const prismaUser = await prisma.user.upsert({
+				where: { userId: user.user_id },
+				create: {
+					displayName: user.display_name!,
+					userId: user.user_id,
+					profileImageUrl: user.profile_image_url,
+				},
+				update: {},
+			});
+			console.log(prismaUser);
```
Comment (Dun-sin) [inline app/api/auth/route.ts:52]:
```suggestion
```

File: app/components/History/index.tsx [hunk 10]
```diff
@@ -1,11 +1,12 @@
-'use client';
+"use client";
```
Comment (Dun-sin) [inline app/components/History/index.tsx:1]:
```suggestion
'use client';
```

File: app/components/History/index.tsx [hunk 11]
```diff
@@ -1,11 +1,12 @@
...
 
-import React, { useEffect, useState } from 'react';
+import React, { useEffect, useState } from "react";
```
Comment (Dun-sin) [inline app/components/History/index.tsx:3]:
```suggestion
import React, { useEffect, useState } from 'react';
```

File: app/components/History/index.tsx [hunk 12]
```diff
@@ -21,11 +22,13 @@ const History = () => {
 		}
 
 		const response = await axios.get(`api/users/${user.user_id}/history`);
+		console.log(response);
+
```
Comment (Dun-sin) [inline app/components/History/index.tsx:26]:
```suggestion
```

File: app/components/History/index.tsx [hunk 13]
```diff
@@ -21,11 +22,13 @@ const History = () => {
...
 		const data = response.data.message.map(
 			({ text, lastUsed }: { text: string; lastUsed: string }) => ({
 				text,
 				lastUsed: new Date(lastUsed),
-			}),
+			})
```
Comment (Dun-sin) [inline app/components/History/index.tsx:31]:
```suggestion
			}),
```

File: app/components/History/index.tsx [hunk 14]
```diff
@@ -34,16 +37,16 @@ const History = () => {
 	return (
 		user && (
 			<div className={`text-fbase w-full`}>
-				<p className='font-bold text-fmd'>Your History</p>
-				<div className='flex flex-wrap justify-between items-center gap-5 w-full mt-2'>
+				<p className="font-bold text-fmd">Your History</p>
+				<div className="flex flex-wrap justify-between items-center gap-5 w-full mt-2">
```
Comment (Dun-sin) [inline app/components/History/index.tsx:41]:
```suggestion
				<p className='font-bold text-fmd'>Your History</p>
				<div className='flex flex-wrap justify-between items-center gap-5 w-full mt-2'>
```

File: app/components/History/index.tsx [hunk 15]
```diff
@@ -34,16 +37,16 @@ const History = () => {
...
 						history.map(({ text, lastUsed }) => (
 							<HistoryCard text={text} lastUsed={lastUsed} key={text} />
 						))
 					) : (
-						<p className='flex items-center font-light text-fsm'>
-							You haven't used HearitFresh yet{' '}
-							<span className='icon-[fluent-emoji--sad-but-relieved-face]' />
+						<p className="flex items-center font-light text-fsm">
+							You haven't used HearitFresh yet{" "}
+							<span className="icon-[fluent-emoji--sad-but-relieved-face]" />
```
Comment (Dun-sin) [inline app/components/History/index.tsx:49]:
```suggestion
						<p className='flex items-center font-light text-fsm'>
							You haven't used HearitFresh yet{' '}
							<span className='icon-[fluent-emoji--sad-but-relieved-face]' />
```

File: app/lib/db/index.ts [hunk 16]
```diff
@@ -18,79 +19,101 @@ export async function addUserHistory(
...
+			await prisma.user.update({
+				where: { userId },
+				data: { history: currentHistory },
+			});
+			// await sql`
+			//   UPDATE users
+			//   SET history = history || ${JSON.stringify([newObject])}::jsonb
+			//   WHERE user_id = ${userId};
+			// `;
+			console.log("New history entry added");
```
Comment (Dun-sin) [inline app/lib/db/index.ts:58]:
```suggestion
```

File: app/lib/db/index.ts [hunk 17]
```diff
@@ -18,79 +19,101 @@ export async function addUserHistory(
...
+		await prisma.user.update({
+			where: { userId },
+			data: { history: updatedHistory },
+		});
+		//* former vercel postgres sql code */
+		// await sql`
+		//   UPDATE users
+		//   SET history = ${JSON.stringify(updatedHistory)}::jsonb
+		//   WHERE user_id = ${userId};
+		// `;
```
Comment (Dun-sin) [inline app/lib/db/index.ts:93]:
```suggestion
```

File: app/lib/db/index.ts [hunk 18]
```diff
@@ -18,79 +19,101 @@ export async function addUserHistory(
...
-): Promise<{ rows: { history: HistoryEntry[] }[] }> {
+	userId: string
+): Promise<HistoryEntry[] | null | undefined> {
 	try {
-		return await sql`
-      SELECT history FROM users WHERE user_id = ${userId};
-    `;
+		// return await sql`
+		//   SELECT history FROM users WHERE user_id = ${userId};
+		// `;
```
Comment (Dun-sin) [inline app/lib/db/index.ts:109]:
```suggestion
```

**Review by Dun-sin — APPROVED** [review]

**Comment by Dun-sin** [comment]
thanks @divineamunega !!
